let data = {
    1994: {
      text: "Duas grandes vitórias da campanha do Greenpeace. Em maio de 1994, a Comissão Internacional da Baleia estabelece um santuário de baleias na Antártica (seção Agenda Ambiental). Após 10 anos de campanha do Greenpeace sobre comércio tóxico, 65 países assinaram a Convenção de Basileia que proíbe a exportação de todos os resíduos perigosos da Organização para Cooperação e Desenvolvimento Económico (OCDE) para países não pertencentes à OCDE.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/0c10f247-greenpeace_international_annualreport1994.pdf" style="color: white;">Read the full report</a></li>'
    },
  
    1995: {
      text: "Leia sobre os testes nucleares franceses e os planos da Shell de despejar a plataforma de petróleo Brent Spar no Mar do Norte. Você também pode descobrir mais sobre como a química do cloro ameaça nossa saúde e o futuro, juntamente com os contratempos na luta para proteger a camada de ozono",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/08cf5e73-greenpeace_international_annualreport1995.pdf" style="color: white;">Read the full report</a></li>'
    },
    1996: {
      text: "EUA, Rússia, França, China e Reino Unido assinam o Tratado de Proibição Completa de Testes (CTBT). O Greenpeace destaca seu compromisso global, virando-se para o leste e abrindo um escritório em Hong Kong como primeiro passo para estabelecer o Greenpeace na China. Organismos geneticamente modificados e energia solar também aparecem no relatório.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/711bca09-greenpeace_international_annualreport1996.pdf" style="color: white;">Read the full report</a></li>'
    },
    1997: {
      text: "Este é o primeiro ano do Greenpeace na China. Os destaques do relatório incluem o acordo climático de Kyoto, uma expedição que documenta o rompimento das prateleiras de gelo da Antártica e ações para impedir o desmatamento nas antigas florestas tropicais do Canadá. Investigações científicas revelam que as crianças são expostas a produtos químicos nocivos dos brinquedos macios de PVC (cloreto de polivinila) e que a usina de reprocessamento nuclear de La Hague está emitindo altos níveis de radiação no mar.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/d7b11a4b-greenpeace_international_annualreport1997.pdf" style="color: white;">Read the full report</a></li>'
    },
    1998: {
      text: "1998 foi o Ano Internacional dos Oceanos da ONU. O Greenpeace faz campanha há muito tempo para proteger os oceanos, e nossos esforços são recompensados ​​com um acordo histórico que proíbe o despejo de instalações offshore como o Brent Spar e a eliminação progressiva de descargas de resíduos radioativos e tóxicos no Atlântico nordeste. Após 15 anos de campanha do Greenpeace, a UE decide eliminar gradualmente as redes de deriva. Também em 1998, a gigante madeireira MacMillan Bloedel anuncia que vai eliminar gradualmente suas operações claras nas florestas tropicais do Canadá. O Greenpeace voa de balão sobre o Taj Mahal para protestar contra testes de armas nucleares na Índia e no Paquistão.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/19432754-greenpeace_international_annualreport1998.pdf" style="color: white;">Read the full report</a></li>'
    },
    1999: {
      text: "Greenpeace refletem as atividades da campanha do ano. Ativistas do Greenpeace estão na linha de fogo enquanto a Noruega e o Japão continuam baleias. Nossos cientistas revelam que Bhopal na Índia, local de um dos piores desastres químicos tóxicos do mundo em 1984, ainda está altamente contaminado. O Greenpeace estabelece uma base em Manaus, Brasil, para ajudar a proteger a Amazônia.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/7d26362e-greenpeace_international_annualreport1999.pdf" style="color: white;">Read the full report</a></li>'
    },
    2000: {
      text: "Relatório indisponível",
      links: null
    },
    2001: {
      text: "Um homem afro-americano, cuja família foi devastada pela poluição química, discursa para os delegados, que mais tarde negociaram o Tratado de Estocolmo para limitar a poluição química. Um ativista do Greenpeace conta como os confrontos com pescadores piratas nas profundezas do Oceano Atlântico ajudaram a conquistar a proteção de espécies ameaçadas de atum.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/3f773192-greenpeace_international_annualreport2001.pdf" style="color: white;">Read the full report</a></li>'
    },
    2002: {
      text: "Visão, Movimento, Espírito: Brincando de gato e rato com baleeiros no Oceano Antártico, enfrentando ameaças de morte de madeireiros ilegais na Amazônia, atravessando a Groenlândia por trenós puxados por cães.<br>É tudo em um dia de trabalho para o Greenpeace, e essas são apenas algumas das histórias do relatório anual de 2002 - além, é claro, dos fatos e números financeiros e relatórios de cada área da campanha.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/d64878f4-greenpeace_international_annualreport2002.pdf" style="color: white;">Read the full report</a></li>'
    },
    2003: {
      text: "Existe um grande número de pessoas em todos os continentes comprometidas com o bem comum e que não estão mais dispostas a aceitar as agendas de governos tímidos ou ineptos ou de empresas sem escrúpulos. Esse movimento social global foi descrito como a “segunda superpotência emergente” e é composto por milhões de pessoas dedicadas à proteção ambiental, direitos humanos e desenvolvimento social. O crescimento contínuo do Greenpeace - conforme apresentado neste relatório anual - mostra que mesmo em tempos economicamente difíceis, as pessoas têm uma visão de um mundo diferente. Esta é a nossa melhor esperança para um futuro melhor.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/12ca5c14-greenpeace_international_annualreport2003.pdf" style="color: white;">Read the full report</a></li>'
    },
    2004: {
      text: "Crimes ambientais acontecem diariamente sem governo, tribunal, polícia ou autoridade a quem recorrer. Não podemos confiar apenas nos governos para agir e fazer mudanças. Nós podemos confiar nas pessoas. A segunda superpotência do mundo pode guiar a mudança, de fato provocá-la. E onde as pessoas se reúnem para mudar, você encontrará o Greenpeace.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/cd9c0a9f-greenpeace_international_annualreport2004.pdf" style="color: white;">Read the full report</a></li>'
    },
    2005: {
      text: "finalmente se tornou lei. Demorou muito tempo para chegar aqui - mais de dez anos - e é apenas o começo da batalha, mas Kyoto é mais do que reduzir as emissões de gases de efeito estufa. Um de seus resultados mais empolgantes é provar que pessoas de diversas comunidades do mundo estão aprendendo a trabalhar juntas para resolver problemas ambientais globais.<br>O poder das pessoas é o futuro das campanhas ambientais, e este ano tivemos algumas vitórias emocionantes usando a Internet para reunir pessoas de todo o mundo para pressionar empresas e políticos - exigindo mudanças através do 'ciberativismo'. No início do ano, a Sony Ericsson se tornou a mais recente gigante mundial da eletrónica a anunciar que eliminaria os produtos químicos tóxicos de seus produtos após nossa ação on-line na qual milhares de pessoas comuns participaram para pressionar as empresas de eletrónicos a ficarem limpas...",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/fabfb751-greenpeace_international_annualreport2005.pdf" style="color: white;">Read the full report</a></li>'
    },
    2006: {
      text: "Verdades inconvenientes e aliados improváveis ​​combinados em 2006 para torná-lo um ano notável para o Greenpeace e o meio ambiente. O Greenpeace faz campanha pela proteção do clima há duas décadas e está em uma posição única para liderar os anos difíceis: promover soluções radicais e se opor a falsas promessas. Nossa independência financeira - não recebemos dinheiro de governos ou corporações - e a adesão aos princípios de ação direta pacífica e não violenta dão um enorme apoio às soluções que propomos. Nosso longo envolvimento no debate climático significa que podemos manter os políticos sob suas promessas e garantir que o novo 'esverdeamento dos negócios', ou Responsabilidade Social Corporativa, não seja uma venda branda, desprovida de ação árdua, mas algo que se combinará para manter aquecimento global a um nível gerenciável.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/f4b36653-greenpeace_international_annualreport2006.pdf" style="color: white;">Read the full report</a></li>'
    },
    2007: {
      text: "Ao ganhar o Prémio Nobel da Paz de 2007, Al Gore disse que não conseguia entender por que os jovens não estavam acorrentados a estações de energia a carvão.<br>Eles são ... e nós também.<br>Agir permanece no coração do Greenpeace. Nossas ações não violentas acontecem em todas as partes do mundo e o número de ativistas continua a crescer. Mantemos nossa independência, aceitando nomoney de empresas ou governos. Mas, queremos fazer mais do que agir pelos outros; queremos agir com os outros. Hoje, é tão importante para o Greenpeace que ajudemos outras pessoas a tomarem medidas significativas quanto é que nós mesmos tomamos medidas.<br>Nossas soluções estabelecem uma visão para um futuro verde e pacífico. Eles são projetados para beneficiar o planeta e seu povo. Grandes problemas precisam de grandes soluções e ações coletivas: o Greenpeace está pronto para ambos.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/9ed4ca8b-greenpeace_international_annualreport2007.pdf" style="color: white;">Read the full report</a></li>'
    },
    2008: {
      text: "Ao longo de 2008, o Greenpeace trabalhou não apenas para destacar as ameaças das mudanças climáticas, mas também para mostrar as oportunidades e soluções que o enfrentamento das mudanças climáticas pode trazer.<br>A evolução do Greenpeace Energy [R] mostra como substituir os combustíveis fósseis de maneira rápida e completa. Nós o desenvolvemos em parceria com a Agência Espacial Alemã e universidades de todo o mundo. Ele suporta projeções atuais de crescimento populacional e econômico. Ele usa tecnologias existentes e rejeita tecnologias não comprovadas de captura e armazenamento de carbono e energia nuclear perigosa.<br>Nosso plano 'Florestas para o clima' descreve como o desmatamento pode ser interrompido até 2015 para áreas prioritárias como a Amazônia, o Congo e as florestas paradisíacas da Indonésia e Papua Nova Guiné e até 2020 em todo o mundo. Ele mostra como parar o desmatamento investindo dinheiro arrecadado nos mercados de carbono em proteção florestal e implementando-o em escala global como evitar o risco de o desmatamento ser simplesmente deslocado.<br>Nosso relatório 'Cool Farming' descreve como sistemas agrícolas sustentáveis ​​podem alimentar o mundo e reduzir as emissões de fertilizantes e animais, devido às mudanças climáticas. Nosso apelo por uma rede global de grandes reservas marinhas totalmente protegidas, cobrindo 40% de nossos oceanos, não apenas restaurará a saúde dos estoques de peixes e protegerá a vida dos oceanos da destruição e colapso de habitats, mas também tornará nossos oceanos mais resistentes às devastações de peixes. das Alterações Climáticas.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/99f47c4f-greenpeace_international_annualreport2008.pdf" style="color: white;">Read the full report</a></li>'
    },
    2009: {
      text: "Dezembro de 2009 - a Conferência das Nações Unidas sobre Mudança Climática, em Copenhague, onde as negociações foram feitas para evitar mudanças climáticas catastróficas. Juntamente com uma ampla coalizão de grupos da sociedade civil, o Greenpeace trabalhou incansavelmente - sob a bandeira da Campanha Global de Ação Climática (GCCA), da qual éramos um membro fundador - para gerar o interesse público e a pressão necessária para tornar essas conversações um sucesso.<br>Essa pressão obrigou cerca de 120 Chefes de Estado a comparecerem a uma das maiores reuniões de líderes mundiais de todos os tempos. No entanto, apesar do claro apelo público a um acordo climático justo, ambicioso e juridicamente vinculativo (FAB), tudo o que produziram foi um débil Acordo de Copenhague de três páginas.<br>Agora está claro que a única maneira de grandes mudanças acontecerem é se a sociedade civil tomar o poder e obrigar políticos e líderes empresariais a agir. Devemos ter uma opinião sobre como será o nosso futuro e o futuro de nossos filhos. Devemos fazer com que os líderes políticos e empresariais entendam que, se não agirem para evitar o caos climático, serão substituídos. E para conseguir isso, devemos proteger o direito a protestos não violentos.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/1f27c590-greenpeace_international_annualreport2009.pdf" style="color: white;">Read the full report</a></li>'
    },
    2010: {
      text: "O ano foi marcado pela devastação que a busca incansável e imprudente pelo lucro pode causar: uma tragédia humana e uma enorme devastação ambiental, social e econômica que durará uma geração ou mais. Observamos horrorizados o derramamento de petróleo de um poço de águas profundas no Golfo do México. A indústria do petróleo parecia despreparada e impotente para detê-la.<br>O desastre do Deepwater Horizon forneceu mais um motivo pelo qual o mundo deveria acabar com a dependência de combustíveis fósseis em declínio e adotar uma evolução da Energy [R] baseada no uso inteligente de fontes de energia renováveis.<br>Ao longo do ano, desafiamos as empresas a se tornarem líderes na luta para evitar as mudanças climáticas. Nós os desafiamos a limpar suas cadeias de suprimentos e abordar seus papéis na destruição ambiental. Exigimos que eles defendessem políticas para proteger o meio ambiente e o clima.<br>E aproveitamos o poder dos consumidores, exortando-os a votar no bolso e exigir bens e serviços que não custam à Terra. Temos feito campanhas cada vez mais com nossos apoiadores para que as principais marcas saibam que não compraremos destruição ambiental.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/378d1ec0-greenpeace_international_annualreport2010.pdf" style="color: white;">Read the full report</a></li>'
    },
    2011: {
      text: "2011 foi o ano em que o Greenpeace comemorou 40 anos como organização de campanha; Embora o ambiente possa estar ameaçado em 1971, ele está em estado de crise hoje. Como os líderes políticos e industriais do mundo não estão dispostos a evitar o caos climático, as áreas da floresta mundial são destruídas diariamente, o Ártico sob ameaça e o consumo insustentável em todos os países industrializados - a urgência de nosso trabalho está aumentando exponencialmente.<br>Nesse contexto, o Greenpeace expandiu e fortaleceu sua mobilização e capacitação de pessoas em todo o mundo para agir.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/fb46f646-greenpeace_international_annualreport2011.pdf" style="color: white;">Read the full report</a></li>'
    },
    2012: {
      text: "Com o aprofundamento da crise ambiental e os impactos das mudanças climáticas sendo sentidos em todo o mundo, nosso trabalho em 2012 se mostrou cada vez mais desafiador e exigente. No entanto, concluímos um trabalho notável, executamos campanhas inovadoras e garantimos vitórias ambientais em todo o mundo.<br>Lançamos nossa campanha “Salve o Ártico”, uma iniciativa ousada e motivada por pessoas para traçar uma linha no gelo e dizer àqueles que vasculhariam os confins da Terra pela última gota de óleo: “Você não vai mais longe!”<br>Continuamos nosso trabalho para alcançar o desmatamento zero até 2020 e proteger as florestas globalmente. Em terra e no mar, descobrimos escândalos na indústria pesqueira. Mostramos como, por trás da bela publicidade e do glamour da passarela do mundo da moda, existe uma indústria que contribui para a poluição tóxica que destrói nossas vias navegáveis. E continuamos a destacar a necessidade de investir em energia limpa para enfrentar as mudanças climáticas, expondo os impactos da mineração e queima de carvão.<br>O Greenpeace tem uma base crescente de apoiadores de cerca de 24 milhões; quem trabalha para nós é voluntário, doa, segue, gosta e toma ações on-line. Eles compartilham nosso trabalho e o deles, desafiando a ameaça mais fundamental ao nosso futuro: Apatia. Juntos, fazemos parte de um movimento global crescente, mais conectado do que nunca, e um que entende os vínculos entre verde e paz, e entre equidade e ecologia.",
      links: '<li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/609378ae-greenpeace_international_annualreport2012.pdf" style="color: white;">Read the full report</a></li>'
    },
    2013: {
      text: "Fazer campanha por um futuro pacífico, justo e verde não é mais o trabalho de alguns poucos especializados, mas a luta comum de todos. À medida que a distância entre ricos e pobres aumenta, e o domínio dos antigos sistemas de energia causa mais estragos no mundo natural, nossa luta deve e deve se intensificar.<br>À medida que despejamos enorme energia e paixão em nossas campanhas, também continuamos a evoluir como organização, continuamos a investir em nossa capacidade de projetar e executar campanhas em economias emergentes, para sermos tão fortes no sul global como no norte. . Isso não foi isento de desafios: cometemos alguns erros, especialmente na área de gerir grandes transferências de moeda estrangeira, como você pode ver em nosso relatório financeiro. Nós aprendemos com esses erros, fazemos as alterações necessárias e emergimos mais fortes.<br>Continuamos a investir em campanhas de pessoas, capacitando e catalisando cidadãos de todo o mundo a trazer mudanças sociais e ambientais positivas. Acreditamos que todos os atos de coragem, como os do Ártico 30, nos impulsionam para a frente. Eles inspiram as pessoas a tomarem suas próprias ações, a se juntarem ao crescente movimento global que não aceitará outro futuro além de um que seja verde, pacífico e justo.",
      links: `
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/d8c715a7-greenpeace_international_annualreport2013.pdf" style="color: white;">Read the full report</a></li>
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/7e69ddb5-gpi-combined-financial-statements-2013.pdf" style="color: white;">Financial statements 2013</a></li>
      `
    },
    2014: {
      text: "Agora, na quinta década de existência, o Greenpeace continua a se reinventar. Em vez de aproveitar as glórias do passado, nossa organização está passando por um processo de renovação que nos coloca no caminho de alcançar ainda mais e muito necessárias vitórias significativas no futuro.<br>Como você pode ler neste Relatório Anual, em 2014 alcançamos - com nossos apoiadores - várias vitórias importantes em campanhas em todo o mundo e em uma ampla variedade de países. Conseguimos essas vitórias ao fazer grandes mudanças na forma como trabalhamos. Alcançamos muitos porque continuamos a evoluir.",
      links: `
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/1998b4c4-greenpeace_international_annualreport2014.pdf" style="color: white;">Read the full report</a></li>
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/f4c0b94c-gpi-combined-financial-statements-2014.pdf" style="color: white;">Financial statements 2014</a></li>
      `
    },
    2015: {
      text: "O Greenpeace está em um caminho transformacional. Nosso mundo está mudando mais rápido do que em qualquer outro momento da história humana. Testemunhamos rápidas mudanças na saúde de nosso planeta, dos oceanos para a atmosfera, no crescimento económico, na inovação tecnológica e na crescente interconexão via Internet e nos mídia sociais. Essas forças impulsionam nossa mudança organizacional e, em 2015, o Greenpeace continuou a implementar uma nova maneira de trabalhar, para que nos tornássemos uma organização mais capacitadora, mais engajada e mais eficaz à medida que olharmos para os próximos 10 anos.<br>Neste Relatório Anual de 2015, o Greenpeace Internacional fornece uma visão geral das atividades realizadas pela rede global do Greenpeace em 2015. Como você lerá, o Greenpeace avançou ainda mais em direção à campanha “motivada por pessoas”, engajando e trabalhando ao lado de outras pessoas para fazer mudanças em seus negócios. próprios quintais. Cada vez mais, também concentramos nossa atenção no que são as causas principais dos problemas, para que possamos projetar nossas campanhas para enfrentar o que está criando os problemas em primeiro lugar ou atrasando as soluções.",
      links: `
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/f10f4d8b-greenpeace_international_annualreport2015.pdf" style="color: white;">Read the full report</a></li>
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/d654f3a5-gpi-combined-financial-statements-2015.pdf" style="color: white;">Financial Statements 2015</a></li>
      `
    },
    2016: {
      text: "Nosso planeta e nosso povo estão mais interconectados do que qualquer rede mundial que possamos criar. O que afeta uma parte, afeta a outra e a proteção ambiental está intrinsecamente ligada à justiça social.<br>No ano passado, nos conectamos em protestos climáticos; com anciãos trabalhando para salvar a Amazônia e o Ártico; avós e jovens processando governos por causa das mudanças climáticas. Ficamos impressionados com o poder do povo e queremos agradecer por tudo que você fez.<br>Juntos, alcançamos uma grande quantidade, mas todos sabemos que há muito mais a ser feito. Este relatório é um instantâneo de alguns dos trabalhos que fizemos juntos, e esperamos que você se conecte com as pessoas e suas histórias. Precisamos que você continue a fazer parte do movimento global imparável por um planeta limpo, verde e justo.",
      links: `
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/6188faf2-greenpeace_international_annualreport2016.pdf" style="color: white;">Annual Report 2016</a></li>
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/11/fdae7835-gpi-combined-financial-statements-2016.pdf" style="color: white;">Financial Statements 2016</a></li>
      `
    },
    2017: {
      text: "Não poderíamos ter feito isso sem você. Somos gratos a todos os nossos apoiadores por nos apoiarem, por estarem no centro do trabalho do Greenpeace Internacional no ano passado e queremos ter um momento para compartilhar nosso Relatório Anual 2017 com você e celebrar nossas conquistas coletivas.<br>Nem tudo o que fazemos é uma manchete. Mas tudo o que fazemos foi possível graças ao seu apoio. Milhões de pessoas adicionaram seu nome, sua voz, sua presença e sua paixão a petições, ações, telefonemas, e-mails e marchas em todo o mundo, defendendo as pessoas e o planeta.<br>Esperamos que você seja tão inspirado quanto os desafios e conquistas que compartilhamos em 2017 e continue trabalhando juntos para criar um planeta justo, igual, verde e pacífico.",
      links: `
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/10/01501847-2017-fs-gpi-consolidated-final-signed_-08.10.2018.pdf" style="color: white;">Financial Statements GPI 2017</a></li>
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2018/10/86cb1e92-independent-auditors-opinion-2017.pdf" style="color: white;">Independent Auditors’ opinion 2017</a></li>
      `
    },
    2018: {
      text: "Em 2018, o Greenpeace trabalhou diligentemente para encontrar maneiras de fazer mudanças rápidas nesses tempos urgentes. Continuamos a nos concentrar mais profundamente na interrupção dos sistemas, na dinâmica de energia e nas mentalidades que sustentam as indústrias agrícolas e de energia fracassadas e destrutivas.",
      links: `
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2019/06/de3fd269-gpi-combined-financial-statements-2018.pdf" style="color: white;">GPI Combined Financial Statements 2018</a></li>
        <li><a href="https://storage.googleapis.com/planet4-international-stateless/2019/07/11d5a6b1-greenpeace_international_annual_report_2018.pdf" style="color: white;">Greenpeace International Annual Report 2018</a></li>
      `
    }
  }